# Generated by Django 3.0.7 on 2020-09-30 18:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(blank=True, default='profiles/anon_user.png', null=True, upload_to='profiles', verbose_name='Аватарка профиля')),
                ('first_name', models.CharField(blank=True, default='Имя', max_length=30, null=True, verbose_name='Имя')),
                ('second_name', models.CharField(blank=True, default='Фамилия', max_length=30, null=True, verbose_name='Фамилия')),
                ('middle_name', models.CharField(blank=True, default='Отчество', max_length=30, null=True, verbose_name='Отчество')),
                ('number_phone', models.CharField(blank=True, default='Не задано', max_length=15, null=True, verbose_name='Номер телефона')),
                ('status', models.CharField(blank=True, choices=[('Работает', 'Работает'), ('Отпуск', 'Отпуск'), ('Больничный', 'Больничный'), ('Уволен', 'Уволен')], default='Не задано', max_length=15, null=True, verbose_name='Статус')),
                ('money', models.IntegerField(blank=True, default=0, null=True, verbose_name='Деньги')),
                ('position', models.CharField(blank=True, default='Не задано', max_length=50, null=True, verbose_name='Должность')),
                ('department', models.CharField(blank=True, default='Не задано', max_length=50, null=True, verbose_name='Отдел')),
                ('role', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Админ'), (2, 'Модер'), (3, 'Пользователь')], null=True, verbose_name='Роль')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Профиль',
                'verbose_name_plural': 'Профили',
                'ordering': ['user'],
            },
        ),
    ]
