# Generated by Django 3.0.7 on 2020-11-18 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alfastaff_account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, default='images/profiles/anon_user.png', null=True, upload_to='profiles', verbose_name='Аватарка профиля'),
        ),
    ]
