# Generated by Django 3.0.7 on 2020-06-22 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alfastaff_account', '0004_auto_20200622_2123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='status',
            field=models.CharField(blank=True, choices=[('Работает', 'Работает'), ('Отпуск', 'Отпуск'), ('Больничный', 'Больничный'), ('Уволен', 'Уволен')], max_length=15, null=True),
        ),
    ]
