# Generated by Django 3.0.7 on 2020-06-24 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alfastaff_account', '0005_auto_20200622_2245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, default='anon_user.png', null=True, upload_to='images/profiles'),
        ),
    ]
