# Generated by Django 3.0.7 on 2020-06-24 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alfastaff_account', '0006_auto_20200624_1458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, default='anon_user.png', null=True, upload_to='profiles'),
        ),
    ]
