# Generated by Django 3.0.7 on 2020-06-25 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alfastaff_account', '0008_auto_20200625_1539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='department',
            field=models.CharField(blank=True, default='Не задано', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='number_phone',
            field=models.CharField(blank=True, default='Не задано', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='points',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='position',
            field=models.CharField(blank=True, default='Не задано', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='status',
            field=models.CharField(blank=True, choices=[('Работает', 'Работает'), ('Отпуск', 'Отпуск'), ('Больничный', 'Больничный'), ('Уволен', 'Уволен')], default='Не задано', max_length=15, null=True),
        ),
        migrations.AlterModelTable(
            name='profile',
            table='Профиль',
        ),
    ]
