# Generated by Django 3.0.7 on 2020-06-25 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alfastaff_account', '0009_auto_20200625_1603'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'Профиль', 'verbose_name_plural': 'Профиль'},
        ),
    ]
