# Generated by Django 3.0.7 on 2020-06-25 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alfastaff_account', '0010_auto_20200625_1620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, default='profiles/anon_user.png', null=True, upload_to='profiles'),
        ),
    ]
