# Generated by Django 3.0.7 on 2020-06-29 21:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('alfastaff_account', '0011_auto_20200625_1645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, default='profiles/anon_user.png', null=True, upload_to='profiles', verbose_name='Фотография'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='department',
            field=models.CharField(blank=True, default='Не задано', max_length=50, null=True, verbose_name='Отдел'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='first_name',
            field=models.CharField(blank=True, default='Имя', max_length=30, null=True, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='middle_name',
            field=models.CharField(blank=True, default='Отчество', max_length=30, null=True, verbose_name='Отчество'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='number_phone',
            field=models.CharField(blank=True, default='Не задано', max_length=15, null=True, verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='points',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Бонусы'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='position',
            field=models.CharField(blank=True, default='Не задано', max_length=50, null=True, verbose_name='Должность'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Админ'), (2, 'Модер'), (3, 'Пользователь')], null=True, verbose_name='Роль'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='second_name',
            field=models.CharField(blank=True, default='Фамилия', max_length=30, null=True, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='status',
            field=models.CharField(blank=True, choices=[('Работает', 'Работает'), ('Отпуск', 'Отпуск'), ('Больничный', 'Больничный'), ('Уволен', 'Уволен')], default='Не задано', max_length=15, null=True, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
