# Generated by Django 3.0.7 on 2020-07-14 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alfastaff_account', '0014_auto_20200714_1535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='images/profiles', verbose_name='Фотография'),
        ),
    ]
