# Generated by Django 3.0.7 on 2020-07-14 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alfastaff_account', '0015_auto_20200714_1800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, default='images/profiles/anon_user.png', null=True, upload_to='images/profiles', verbose_name='Фотография'),
        ),
    ]
