# Generated by Django 3.0.7 on 2020-07-20 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alfastaff_account', '0016_auto_20200714_1908'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='avatar_binary',
            field=models.BinaryField(blank=True, verbose_name='Фотография байткод'),
        ),
    ]
