# Generated by Django 3.0.7 on 2020-07-29 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alfastaff_account', '0020_auto_20200724_1503'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'Профиль', 'verbose_name_plural': 'Профили'},
        ),
    ]
