# Generated by Django 3.0.7 on 2020-07-29 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alfastaff_account', '0021_auto_20200729_2020'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ['user'], 'verbose_name': 'Профиль', 'verbose_name_plural': 'Профили'},
        ),
        migrations.AlterModelTable(
            name='profile',
            table=None,
        ),
    ]
