# Generated by Django 3.0.7 on 2020-08-02 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alfastaff_account', '0022_auto_20200729_2227'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='avatar_binary',
        ),
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, default='profiles/anon_user.png', null=True, upload_to='profiles', verbose_name='Фотография'),
        ),
    ]
