# Generated by Django 3.0.7 on 2020-06-22 17:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('alfastaff_bonuses', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bonuscard',
            name='balance',
        ),
        migrations.RemoveField(
            model_name='bonuscard',
            name='date_buy',
        ),
        migrations.RemoveField(
            model_name='bonuscard',
            name='status',
        ),
        migrations.RemoveField(
            model_name='bonuscard',
            name='user',
        ),
        migrations.AddField(
            model_name='bonuscard',
            name='image',
            field=models.ImageField(blank=True, default='', null=True, upload_to=''),
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
                ('cost', models.IntegerField(blank=True, null=True)),
                ('date_buy', models.DateTimeField(blank=True, null=True)),
                ('balance', models.IntegerField(blank=True, null=True)),
                ('status', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Одобрено'), (2, 'Отменено'), (3, 'Ожидание')], null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
