# Generated by Django 3.0.7 on 2020-06-22 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alfastaff_bonuses', '0002_auto_20200622_1738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bonuscard',
            name='image',
            field=models.ImageField(blank=True, default='anon_user.png', null=True, upload_to=''),
        ),
    ]
