# Generated by Django 3.0.7 on 2020-06-24 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alfastaff_bonuses', '0003_auto_20200622_2123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bonuscard',
            name='image',
            field=models.ImageField(blank=True, default='anon_user.png', null=True, upload_to='bonuses'),
        ),
    ]
