# Generated by Django 3.0.7 on 2020-06-25 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alfastaff_bonuses', '0004_auto_20200624_1510'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='bonuscard',
            table='Бонусы',
        ),
        migrations.AlterModelTable(
            name='purchase',
            table='Покупки',
        ),
    ]
