# Generated by Django 3.0.7 on 2020-06-25 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alfastaff_bonuses', '0005_auto_20200625_1603'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bonuscard',
            options={'verbose_name': 'Бонусы', 'verbose_name_plural': 'Бонусы'},
        ),
        migrations.AlterModelOptions(
            name='purchase',
            options={'verbose_name': 'Покупки', 'verbose_name_plural': 'Покупки'},
        ),
    ]
