# Generated by Django 3.0.7 on 2020-06-25 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alfastaff_bonuses', '0006_auto_20200625_1620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bonuscard',
            name='image',
            field=models.ImageField(blank=True, default='bonuses/product.jpg', null=True, upload_to='bonuses'),
        ),
    ]
