# Generated by Django 3.0.7 on 2020-06-25 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alfastaff_bonuses', '0007_auto_20200625_1645'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bonuscard',
            options={'verbose_name': 'Товары', 'verbose_name_plural': 'Товары'},
        ),
        migrations.AlterModelTable(
            name='bonuscard',
            table='Товары',
        ),
    ]
