# Generated by Django 3.0.7 on 2020-06-25 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alfastaff_bonuses', '0008_auto_20200625_1702'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bonuscard',
            options={'ordering': ['name'], 'verbose_name': 'Товары', 'verbose_name_plural': 'Товары'},
        ),
    ]
