# Generated by Django 3.0.7 on 2020-06-26 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alfastaff_bonuses', '0009_auto_20200625_1821'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='purchase',
            options={'ordering': ['-id'], 'verbose_name': 'Покупки', 'verbose_name_plural': 'Покупки'},
        ),
    ]
