# Generated by Django 3.0.7 on 2020-06-26 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alfastaff_bonuses', '0010_auto_20200626_1853'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='description',
        ),
        migrations.AddField(
            model_name='purchase',
            name='id_purchase',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='date_buy',
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
