# Generated by Django 3.0.7 on 2020-07-06 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alfastaff_bonuses', '0012_auto_20200629_2132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bonuscard',
            name='image',
            field=models.ImageField(blank=True, default='static/images/bonuses/product.jpg', null=True, upload_to='static/images/bonuses', verbose_name='Фотография'),
        ),
    ]
