# Generated by Django 3.0.7 on 2020-07-06 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alfastaff_bonuses', '0013_auto_20200706_1545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bonuscard',
            name='image',
            field=models.ImageField(blank=True, default='bonuses/product.jpg', null=True, upload_to='bonuses', verbose_name='Фотография'),
        ),
    ]
