# Generated by Django 3.0.7 on 2020-07-08 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alfastaff_bonuses', '0014_auto_20200706_1547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bonuscard',
            name='image',
            field=models.ImageField(blank=True, default='images/bonuses/product.jpg', null=True, upload_to='images/bonuses', verbose_name='Фотография'),
        ),
    ]
