# Generated by Django 3.0.7 on 2020-07-20 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alfastaff_bonuses', '0015_auto_20200708_1121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bonuscard',
            name='image',
            field=models.ImageField(blank=True, default='images/bonuses/incognita.png', null=True, upload_to='images/bonuses', verbose_name='Фотография'),
        ),
    ]
