# Generated by Django 3.0.7 on 2020-07-21 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alfastaff_bonuses', '0016_auto_20200720_1819'),
    ]

    operations = [
        migrations.AddField(
            model_name='bonuscard',
            name='image_binary',
            field=models.BinaryField(blank=True, editable=True, verbose_name='Фотография байткод'),
        ),
    ]
