# Generated by Django 3.0.7 on 2020-07-21 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alfastaff_bonuses', '0017_bonuscard_image_binary'),
    ]

    operations = [
        migrations.AddField(
            model_name='bonuscard',
            name='image_ыек',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='тест'),
        ),
    ]
