# Generated by Django 3.0.7 on 2020-07-21 21:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alfastaff_bonuses', '0019_auto_20200721_2357'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bonuscard',
            name='image_str',
        ),
    ]
