# Generated by Django 3.0.7 on 2020-07-21 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alfastaff_bonuses', '0020_remove_bonuscard_image_str'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bonuscard',
            name='description',
            field=models.CharField(blank=True, max_length=200000, null=True, verbose_name='Описание'),
        ),
    ]
