# Generated by Django 3.0.7 on 2020-07-21 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alfastaff_bonuses', '0021_auto_20200722_0056'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bonuscard',
            old_name='description',
            new_name='image_base64',
        ),
        migrations.RemoveField(
            model_name='bonuscard',
            name='image_binary',
        ),
    ]
