# Generated by Django 3.0.7 on 2020-07-21 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alfastaff_bonuses', '0022_auto_20200722_0106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bonuscard',
            name='image_base64',
            field=models.CharField(blank=True, max_length=200000, null=True, verbose_name='Фотография base64'),
        ),
    ]
