# Generated by Django 3.0.7 on 2020-07-24 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alfastaff_bonuses', '0024_auto_20200722_0115'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bonuscard',
            name='image_base64',
        ),
        migrations.AddField(
            model_name='bonuscard',
            name='image_binary',
            field=models.BinaryField(blank=True, editable=True, verbose_name='Фотография байткод'),
        ),
    ]
