# Generated by Django 3.0.7 on 2020-07-24 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alfastaff_bonuses', '0025_auto_20200724_1346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bonuscard',
            name='image_binary',
            field=models.BinaryField(blank=True, verbose_name='Фотография байткод'),
        ),
    ]
