# Generated by Django 3.0.7 on 2020-07-29 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alfastaff_bonuses', '0026_auto_20200724_1503'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bonuscard',
            options={'ordering': ['name'], 'verbose_name': 'Товар', 'verbose_name_plural': 'Товары'},
        ),
        migrations.AlterModelOptions(
            name='purchase',
            options={'ordering': ['-id'], 'verbose_name': 'Покупка', 'verbose_name_plural': 'Покупки'},
        ),
    ]
