# Generated by Django 3.0.7 on 2020-07-29 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alfastaff_bonuses', '0027_auto_20200729_2020'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='purchase',
            table=None,
        ),
    ]
