# Generated by Django 3.0.7 on 2020-09-30 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alfastaff_products', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='productcard',
            table=None,
        ),
    ]
