# Generated by Django 3.0.7 on 2020-11-18 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alfastaff_products', '0003_auto_20201118_1738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcard',
            name='image',
            field=models.ImageField(blank=True, default='images/products/product.jpg', null=True, upload_to='images/products', verbose_name='Фото'),
        ),
    ]
