# Generated by Django 3.0.7 on 2020-11-19 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alfastaff_products', '0005_transaction'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ['-id'], 'verbose_name': 'Транзакция', 'verbose_name_plural': 'Транзакции'},
        ),
    ]
