# Generated by Django 3.0.7 on 2020-12-06 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alfastaff_task_manager', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='priority',
        ),
        migrations.RemoveField(
            model_name='task',
            name='title',
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(blank=True, choices=[('К работе', 'К работе'), ('В процессе', 'В процессе'), ('Готово', 'Готово')], max_length=15, null=True, verbose_name='Статус'),
        ),
    ]
