# Generated by Django 3.0.7 on 2020-07-29 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PersonnelLoadTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Название')),
                ('date_upload', models.DateField(auto_now=True, null=True, verbose_name='Дата загрузки')),
                ('file_with_table', models.FileField(blank=True, null=True, upload_to='', verbose_name='CSV файл с нагрузкой персонала')),
            ],
            options={
                'verbose_name': 'Таблицы нагрузки персонала',
                'verbose_name_plural': 'Таблицы нагрузки персонала',
                'db_table': 'Таблицы нагрузки персонала',
                'ordering': ['-date_upload'],
            },
        ),
    ]
