# Generated by Django 3.0.7 on 2020-09-30 18:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonnelLoadDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Название')),
                ('date_upload', models.DateField(auto_now=True, null=True, verbose_name='Дата загрузки')),
                ('file_with_table', models.FileField(blank=True, null=True, upload_to='documents', verbose_name='CSV файл с нагрузкой персонала')),
            ],
            options={
                'verbose_name': 'Документ нагрузки персонала',
                'verbose_name_plural': 'Документы нагрузки персонала',
                'db_table': 'Документы нагрузки персонала',
                'ordering': ['-date_upload'],
            },
        ),
        migrations.CreateModel(
            name='ScheduleForOneDay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.CharField(blank=True, max_length=15, null=True, verbose_name='День недели')),
                ('year', models.IntegerField(blank=True, null=True, verbose_name='Год')),
                ('month', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Jun'), (2, 'Feb'), (3, 'Mar')], null=True, verbose_name='Месяц')),
                ('number_day', models.IntegerField(blank=True, null=True, verbose_name='Номер дня в месяце')),
                ('working_hours', models.CharField(blank=True, max_length=30, null=True, verbose_name='Время работы')),
                ('lunch_time', models.CharField(blank=True, max_length=30, null=True, verbose_name='Время обеда')),
                ('technical_break_time', models.CharField(blank=True, max_length=30, null=True, verbose_name='Время тех. перерыва')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользоваетль')),
            ],
            options={
                'verbose_name': 'Расписание сотрудника на день',
                'verbose_name_plural': 'Расписание сотрудников по дням',
                'ordering': ['user'],
            },
        ),
    ]
