# Generated by Django 3.0.7 on 2020-07-29 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alfastaff_shedule', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='personnelloadtable',
            options={'ordering': ['-date_upload'], 'verbose_name': 'Таблица нагрузки персонала', 'verbose_name_plural': 'Таблицы нагрузки персонала'},
        ),
    ]
