# Generated by Django 3.0.7 on 2020-09-30 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alfastaff_shedule', '0002_auto_20200930_2223'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduleforoneday',
            name='holiday',
            field=models.BooleanField(blank=True, null=True, verbose_name='Праздник'),
        ),
    ]
