# Generated by Django 3.0.7 on 2020-07-29 19:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('alfastaff_shedule', '0003_auto_20200729_2039'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailySchedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.CharField(blank=True, max_length=15, null=True, verbose_name='День недели')),
                ('year', models.IntegerField(blank=True, max_length=15, null=True, verbose_name='Номер месяца')),
                ('number_month', models.IntegerField(blank=True, max_length=15, null=True, verbose_name='Номер месяца')),
                ('number_day', models.IntegerField(blank=True, null=True, verbose_name='Номер дня в месяце')),
                ('working_hours', models.CharField(blank=True, max_length=30, null=True, verbose_name='Время работы')),
                ('lunch_time', models.CharField(blank=True, max_length=30, null=True, verbose_name='Время обеда')),
                ('technical_break_time', models.CharField(blank=True, max_length=30, null=True, verbose_name='Время тех. перерыва')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользоваетль')),
            ],
            options={
                'verbose_name': 'Расписание на день',
                'verbose_name_plural': 'Расписания на день',
                'ordering': ['user'],
            },
        ),
    ]
