# Generated by Django 3.0.7 on 2020-11-19 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alfastaff_shedule', '0003_scheduleforoneday_holiday'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduleforoneday',
            name='day_off',
            field=models.BooleanField(blank=True, null=True, verbose_name='Выходной'),
        ),
        migrations.AlterField(
            model_name='scheduleforoneday',
            name='month',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Jun'), (2, 'Feb'), (3, 'Mar'), (4, 'Apr'), (5, 'May'), (6, 'Jun'), (7, 'Jul'), (8, 'Aug'), (9, 'Sep'), (10, 'Oct'), (11, 'Nov'), (12, 'Dec')], null=True, verbose_name='Месяц'),
        ),
    ]
