# Generated by Django 3.0.7 on 2020-07-29 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alfastaff_shedule', '0004_dailyschedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyschedule',
            name='number_month',
            field=models.IntegerField(blank=True, null=True, verbose_name='Номер месяца'),
        ),
        migrations.AlterField(
            model_name='dailyschedule',
            name='year',
            field=models.IntegerField(blank=True, null=True, verbose_name='Номер месяца'),
        ),
    ]
