# Generated by Django 3.0.7 on 2020-07-29 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alfastaff_shedule', '0006_auto_20200729_2240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduleforoneday',
            name='year',
            field=models.IntegerField(blank=True, null=True, verbose_name='Год'),
        ),
    ]
