# Generated by Django 3.0.7 on 2020-07-29 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alfastaff_shedule', '0007_auto_20200729_2250'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scheduleforoneday',
            name='number_month',
        ),
        migrations.AddField(
            model_name='scheduleforoneday',
            name='month',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Jun'), (2, 'Feb'), (3, 'Mar')], null=True, verbose_name='Месяц'),
        ),
    ]
