# Generated by Django 3.0.7 on 2020-08-02 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alfastaff_shedule', '0008_auto_20200729_2258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personnelloaddocument',
            name='file_with_table',
            field=models.FileField(blank=True, null=True, upload_to='documents', verbose_name='CSV файл с нагрузкой персонала'),
        ),
    ]
